### ISSUE TITLE
beforeSend global support async/await

### ISSUE THREAD

**Issue by alvins82** [WebsiteBeaver/far-fetch#2]
I am trying to use auth0 spa plugin and one of its methods to get the access-token to put in authorisation header is asynchronous (getTokenSilently). I would like to use that in beforeSend to setup global Authorisation header but far-fetch doesn't support async beforeSend. Any chance that this can be added?

Axious has something similiar - see below.

```
apiClient.interceptors.request.use(async (config) => {
    const token = await myApp.$auth.getTokenSilently();
    config.headers['Authorization'] = `Bearer ${token}`;
    return config;
}, (error) => {
    return Promise.reject(error);
});
```

**Comment by D-Marc1** [comment]
Hey @alvins82, thanks for the suggestion. I'm always happy to improve `FarFetch`.

This should be no problem. I can change the code to simply detect if the `beforeSend()` function returns a `promise` or is `async` and then `await` it if so.

**Comment by D-Marc1** [comment]
Ok, I just added the ability to create an `async` `beforeSend()`. I haven't written tests yet for this, along with a few other features and fixes I made previously, but try installing the new alpha release,  **1.2.0-1** with `npm i @websitebeaver/far-fetch@next`. I will add testing in the near future as well, but this should work right now. Please let me know if it doesn't.

**Comment by D-Marc1** [comment]
Version 2.0.0 is now released. You can use `async` with `beforeSend()`, `afterSend()`, `dynamicOptions` and `errorHandler()`.
