### ISSUE TITLE
Pass url and current config to the beforeSend() callback

### ISSUE THREAD

**Issue by gbcreation** [WebsiteBeaver/far-fetch#3]
Similarly to what Axios does with request interceptors, it would be useful that the beforeSend() callback receives the called URL and the fetch config. For example, to inject HTTP headers depending on the fetched URL.

**Comment by D-Marc1** [comment]
I can add something like this. Thanks for the suggestion.

**Comment by D-Marc1** [comment]
@gbcreation Just published a new release with this feature added. You can now do the following:

```js
beforeSend({
  url,
  fetchAPIOptions,
  data,
  URLParams,
  files,
  errorMsg,
  errorMsgNoun,
  globalBeforeSend,
  globalAfterSend,
  defaultOptionsUsed,
}) {
  console.log('do this before every request');
},
```

It should be noted that now there's a dedicated function for returning dynamic options:

```js
dynamicOptions() {
  // Use authorization header if token set in localStorage
  if (localStorage.getItem('token')) {
    return {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('token')}`,
      },
    }
  }
},
```

**Comment by gbcreation** [comment]
Awesome! Thank you very muck :+1:
